export const icons = {
  pencil: require('../../assets/images/pencil.png'),
  evolution: require('../../assets/images/evolution.png'),
  journal: require('../../assets/images/journal.png'),
  user: require('../../assets/images/user.png'),
  premium: require('../../assets/images/premium.png'),
  add: require('../../assets/images/add.png'),
  search: require('../../assets/images/search.png'),
  delete: require('../../assets/images/delete.png'),
  email: require('../../assets/images/email.png'),
  compare: require('../../assets/images/compare.png'),
  chart: require('../../assets/images/chart.png'),
  voice: require('../../assets/images/voice.png'),
  setting: require('../../assets/images/setting.png'),
  close: require('../../assets/images/close.png'),
  calendar: require('../../assets/images/calendar.png'),
  lock: require('../../assets/images/lock.png'),
  visible: require('../../assets/images/visible.png'),
  inVisible: require('../../assets/images/inVisible.png'),
  warning: require('../../assets/images/warning.png'),
  google: require('../../assets/images/google.png'),
  facebook: require('../../assets/images/facebook.png'),
  play: require('../../assets/images/play.png'),
  pause: require('../../assets/images/pause.png'),
  share: require('../../assets/images/share.png'),
};
